import Head from "next/head";
import { ReactElement } from "react";

import * as C from "@/components/common/";

type LayoutProps = Required<{
  readonly children: ReactElement;
}>;

export const Layout = ({ children }: LayoutProps) => (
  <>
    <Head>
      <title>Next App with unocss</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <C.Navbar />
    <main className="flex flex-col items-center gap-20px px-12 py-20 text-center font-sans">
      {children}
    </main>
  </>
);
