import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Navbar from "../components/navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App with unocss</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />

      <main className="flex flex-col items-center gap-20px px-12 py-20 text-center font-sans">
        <span text="blue 5xl hover:red" cursor="default">
          Hello Next
        </span>
        <div text="4xl teal-500 " className="i-carbon-car" />

        <Link href="/blog">
          <a className="btn-01 flex items-center">
            <div bg="pink-500" className="flex">
              Blog
              <span>hoge</span>
            </div>
            <div className="i-carbon-arrow-right" />
          </a>
        </Link>
        <relative>
          <btn-01 class="absolute">aaa</btn-01>
        </relative>
        {/* <TopCard /> */}
      </main>
    </>
  );
};

export default Home;
