name: make branch from issue with label
on:
  issues:
    types:
      - labeled
jobs:
  auto-made-branch:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0

      # ラベル名を取得する
      - name: Get label name
        id: label_name
        run: |
          label_type=$(echo ${{ github.event.label.name}})
          if [ $label_type == 'enhancement' ]; then
            branch:'feature/issue${{ github.event.issue.number }}'
          # elif [ $branch_type == 'fix' ] || [ $branch_type == 'hotfix' ]; then
          #   label_name=$(echo "bug")
          # else
          #   label_name=""
          fi
